name: docker-push
on:
  push:
    branches:
      - master

jobs:
  Create-Docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      uses: actions/checkout@v2

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
        IMAGE_NAME: glamworkbench/anu-archives

    - name: Modify readme for DockerHub
      run: |
        sed -r 's/\[(.*)\]\(.*\.ipynb\)/\1/' README.md > index.md
        sed -i '/^<\!-- START RUN INFO/,/^<\!-- END RUN INFO/d;' index.md

    - name: update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: glamworkbench/anu-archives
        readme-filepath: index.md

    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.1.0
      with:
          add: index.md
          message: 'Update from README'
